apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server
        component: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: monstar/nfs-server
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
