apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfs-server
    component: nfs-server
  name: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
  - name: rpcbind
    port: 111
  selector:
    provider: nfs
